services:
  - type: web
    name: trading-pro
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /
        destination: /signin.html
